import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
    page: {
        padding: 40,
        backgroundColor: '#ffffff',
        fontFamily: 'Helvetica'
    },
    header: {
        marginBottom: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e2e8f0',
        paddingBottom: 20,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center'
    },
    brand: {
        fontSize: 10,
        color: '#94a3b8',
        letterSpacing: 2,
        textTransform: 'uppercase'
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#0f172a',
        marginBottom: 6
    },
    subtitle: {
        fontSize: 12,
        color: '#64748b'
    },
    content: {
        marginVertical: 20
    },
    row: {
        flexDirection: 'row',
        marginBottom: 15
    },
    col: {
        flex: 1
    },
    colRight: {
        flex: 1,
        alignItems: 'flex-end'
    },
    colLabel: {
        fontSize: 9,
        color: '#64748b',
        marginBottom: 4,
        textTransform: 'uppercase'
    },
    colValue: {
        fontSize: 12,
        color: '#0f172a',
        fontWeight: 'bold'
    },
    barcodeSection: {
        marginTop: 40,
        alignItems: 'center',
        paddingTop: 20,
        borderTopWidth: 1,
        borderTopColor: '#e2e8f0',
        borderStyle: 'dashed'
    },
    barcodeImage: {
        width: 300,
        height: 80
    },
    codeText: {
        marginTop: 5,
        fontSize: 10,
        color: '#64748b',
        letterSpacing: 2
    },
    footer: {
        position: 'absolute',
        bottom: 30,
        left: 40,
        right: 40,
        alignItems: 'center'
    },
    footerText: {
        fontSize: 8,
        color: '#cbd5e1'
    }
});

interface TicketDocumentProps {
    order: any;
    barcodes: Record<string, string>;
    userName?: string;
}

export const TicketDocument = ({ order, barcodes, userName }: TicketDocumentProps) => (
    <Document>
        {(order.individualTickets || []).map((ticket: any) => (
            <Page key={ticket.id || Math.random()} size="A4" style={styles.page}>
                <View style={styles.header}>
                    <View>
                        <Text style={styles.title}>{order.eventTitle}</Text>
                        <Text style={styles.subtitle}>{order.eventLocation}</Text>
                        <Text style={styles.subtitle}>
                            {new Date(order.eventDate).toLocaleDateString()} at {new Date(order.eventDate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                        </Text>
                    </View>
                    <Text style={styles.brand}>Tickex Ticket</Text>
                </View>

                <View style={styles.content}>
                    <View style={styles.row}>
                        <View style={styles.col}>
                            <Text style={styles.colLabel}>Ticket Type</Text>
                            <Text style={styles.colValue}>{ticket.type}</Text>
                        </View>
                        <View style={styles.colRight}>
                            <Text style={styles.colLabel}>Price</Text>
                            <Text style={styles.colValue}>
                                SZL {order.tickets.find((t: any) => t.type === ticket.type)?.price || '0.00'}
                            </Text>
                        </View>
                    </View>

                    <View style={styles.row}>
                        <View style={styles.col}>
                            <Text style={styles.colLabel}>Attendee</Text>
                            <Text style={styles.colValue}>{userName || 'Valued Customer'}</Text>
                        </View>
                        <View style={styles.colRight}>
                            <Text style={styles.colLabel}>Reference</Text>
                            <Text style={styles.colValue}>{order.id}</Text>
                        </View>
                    </View>
                </View>

                <View style={styles.barcodeSection}>
                    {barcodes[ticket.code] && (
                        <Image src={barcodes[ticket.code]} style={styles.barcodeImage} />
                    )}
                    <Text style={styles.codeText}>{ticket.code}</Text>
                </View>

                <View style={styles.footer}>
                    <Text style={styles.footerText}>
                        Scan this barcode at the event entrance. This ticket is unique and cannot be duplicated.
                    </Text>
                    <Text style={[styles.footerText, { marginTop: 4 }]}>
                        Generated by Tickex
                    </Text>
                </View>
            </Page>
        ))}
    </Document>
);
